CREATE TABLE part_of_speech (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word TEXT NOT NULL,
    translation TEXT,

    CONSTRAINT pk_part_of_speech PRIMARY KEY (id),
    CONSTRAINT uq_part_of_speech_word UNIQUE (word),
    CONSTRAINT chk_part_of_speech_word_not_empty CHECK (char_length(word) > 0)
);

CREATE TABLE dictionary (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word TEXT NOT NULL,

    CONSTRAINT pk_dictionary PRIMARY KEY (id),
    CONSTRAINT uq_dictionary_word UNIQUE (word),
    CONSTRAINT chk_dictionary_word_not_empty CHECK (char_length(word) > 0)
);

CREATE TABLE dictionary_translation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    translation TEXT NOT NULL,
    dictionary_id INTEGER NOT NULL,
    part_of_speech_id INTEGER NOT NULL,

    CONSTRAINT pk_dictionary_translation PRIMARY KEY (id),

    CONSTRAINT fk_dictionary_translation_dictionary
        FOREIGN KEY (dictionary_id)
        REFERENCES dictionary(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_dictionary_translation_part_of_speech
        FOREIGN KEY (part_of_speech_id)
        REFERENCES part_of_speech(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT uq_dictionary_translation_unique
        UNIQUE (dictionary_id, part_of_speech_id, translation),

    CONSTRAINT chk_dictionary_translation_translation_not_empty
        CHECK (char_length(translation) > 0)
);

CREATE INDEX idx_dictionary_translation_dictionary_id
ON dictionary_translation(dictionary_id);

CREATE INDEX idx_dictionary_translation_part_of_speech_id
ON dictionary_translation(part_of_speech_id);

CREATE TABLE vocabulary_source (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    url TEXT NOT NULL,

    CONSTRAINT pk_vocabulary_source PRIMARY KEY (id),
    CONSTRAINT chk_vocabulary_source_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT chk_vocabulary_source_url_not_empty CHECK (char_length(url) > 0)
);

CREATE TABLE learned_vocabulary (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sentence TEXT NOT NULL,
    translation TEXT NOT NULL,
    vocabulary_source_id INTEGER NOT NULL,
    dictionary_translation_id INTEGER NOT NULL,

    CONSTRAINT pk_learned_vocabulary PRIMARY KEY (id),

    CONSTRAINT fk_learned_vocabulary_vocabulary_source
        FOREIGN KEY (vocabulary_source_id)
        REFERENCES vocabulary_source(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_learned_vocabulary_dictionary_translation
        FOREIGN KEY (dictionary_translation_id)
        REFERENCES dictionary_translation(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_learned_vocabulary_sentence_not_empty CHECK (char_length(sentence) > 0),
    CONSTRAINT chk_learned_vocabulary_translation_not_empty CHECK (char_length(translation) > 0)
);

CREATE INDEX idx_learned_vocabulary_vocabulary_source_id
ON learned_vocabulary(vocabulary_source_id);

CREATE INDEX idx_learned_vocabulary_dictionary_translation_id
ON learned_vocabulary(dictionary_translation_id);
